### ISSUE TITLE
DOC Make initial website

### ISSUE THREAD

**Issue by Micky774** [Micky774/slsdm#14]
### Background

Create a website. This doesn't need to be much at first, but will serve as a good place to start building up documentation, especially if the project ever gets more complex.

### TODO
- [ ] Create initial landing page/index
- [ ] Port `README.md` documentation to website
    - [ ] Create setup/install page
    - [ ] Create page discussing SIMD specification
    - [ ] Create tutorial page including example script
- [ ] Investigate in-browser-demo strategies (e.g. binder)
