### ISSUE TITLE
ENH Introduce other metrics present in scikit-learn

### ISSUE THREAD

**Issue by Micky774** [Micky774/slsdm#15]
### Background

This library ought to provide accelerated implementations of popular metrics, specifically including those presently available in scikit-learn. Currently, we already support a few of the more common ones, however many of the Boolean metrics and more specific ones are yet unadded.

### TODO
- [ ] Boolean metrics
    - [ ] jaccard
    - [ ] dice
    - [ ] matching
    - [ ] rogerstanimoto
    - [ ] russellrao
    - [ ] sokalmichener
    - [ ] sokalsneath
- [ ] Integer vector metrics
    - [ ] hamming
    - [ ] canberra
    - [ ] braycurtis
- [ ] 2D real vector metrics
    - [ ] haversine
- [ ] Real vector metrics
    - [ ] mahalanobis
